
export const text = {
  SignUp: "Đăng ký",
  SignUpSucces: "Đăng ký thành công",
  Login: "Đăng nhập",
  LoginSuccess: "Đăng nhập thành công",
  Password: "Mật Khẩu",
  UserName: "Tên người dùng",
  RepeatPassword: "Nhập lại mật khẩu",
  SignUpBottomText: "Đã có tài khoản ? Đăng nhập ngay",
  LoginBottomText: "Chưa có tài khoản ? Đăng ký ngay",
  Remember: "Ghi nhớ đăng nhập",
  NewQuestion: "Tạo câu hỏi mới",
  AllQuestion: "Tất cả câu hỏi",
  AllUnapprovedQuestion: "Tất cả câu hỏi chưa được duyệt",
  Approve: "Đã duyệt",
  ApproveAction: "Duyệt bài",
  Unapproved: "Chưa duyệt",
  UnapprovedQuestion: "Câu hỏi đang chờ",
  AskQuestion: "Đặt câu hỏi",
  EditQuestion: "Sửa câu hỏi",
  EditQuestionAction: "Sửa",
  Title: "Tiêu đề",
  TitleDesc:
    "Hãy miêu tả cụ thể và tưởng tượng bạn đang đặt câu hỏi cho một người khác",
  Body: "Nội dung",
  BodyDesc:
    "Bao gồm tất cả thông tin mà người đọc sẽ cần để trả lời câu hỏi của bạn",
  Tag: "Thẻ",
  TagDesc: "Thêm tối đa 5 thẻ liên quan đến câu hỏi",
  FieldRequierd: "Trường này không thể bỏ trống",
  FieldLengthRequierd: "Trường cần tối thiêu 6 ký tự",
  TagRequierd: "Trường này chỉ có thể nhận 5 thẻ",
  CreateQuestion: "Tạo câu hỏi",
  NoResult: "Không có kết quả",
  TagPageDesc:
    "Thẻ là một từ khóa hoặc nhãn phân loại câu hỏi của bạn với các câu hỏi tương tự khác",
  NewTag: "Tạo thẻ mới",
  Img: "Ảnh minh hoạ",
  AddImg: "Chọn tối đa 5 ảnh để miêu tả câu hỏi",
  ImgMax: "Trường này chỉ nhận tối đa 5 ảnh",
  UserProfile: "Trang cá nhân",
  LogOut: "Đăng xuất",
  Home: "Trang chủ",
  FileSizeErr: "Ảnh quá nặng",
  TagName: "Tên thẻ",
  TagNameDesc: "Tên miêu tả thẻ",
  TagDescription: "Mô tả nội dung thẻ",
  TagDescHint: "Hãy miểu tả cụ thể về thẻ này",
  Createtag: "Tạo thẻ",
  Comment: "Bình luận",
  ApproveActionSuc: 'Duyệt thành công',
  Edit: 'Sửa',
  Open: 'Mở',
  author: 'Người đăng :',
  createAt: 'Được tạo từ :',
  Answered: 'Có đáp án',
  AnswerDesc: 'Câu trả lời được người đăng hoặc quản trị viên cho là đúng',
  ChooseAnswer: 'Chọn làm đáp án',
  Success: "Thao tác thành công",
  changePassword: 'Đổi mật khẩu',
  newPassword: 'Mật khẩu mới',
  wrong_repeat_password: 'Mật khẩu nhập lại chưa chính xác',
  delete_question: 'Xoá bài viết',
  set_role_admin: 'Thêm làm quản trị viên',
  set_role_member: 'Gỡ quản trị viên',
};
