export const endPoints = {
  blog: "blog/",
  approveBlog: "blog",
  unapproved: "unapproved",
  approve: "approve",
  findBlogs: "search/",
  login: "/login",
  register: "/signup",
  user: "/user/",
  tag: "/tag",
  createTag: "/tag/newTag",
  currentUser: "user/current_user",
  blockUser: "user/block",
  comment: "/comment/",
  addComment: "/comment/add",
  hiddenComment: "/comment/hidden",
  getSign: "/sign_cloudinary",
  blogEdit: 'blog/edit',
  chooseAnswer: "blog/answer",
  change_password: '/change_password',
  change_role: 'user/set_role'
};
