export const endPoints = {
  blog: "blog/",
  unapproved: "unapproved",
  approve: "approve",
  findBlogs: "search/",
  login: "/login",
  register: "/signup",
  user: "/user/",
  tag: "/tag",
  createTag: "/tag/newTag",
  currentUser: "user/current_user",
  comment: "/comment/",
  addComment: "/comment/add",
  getSign: "/sign_cloudinary",
};
